
# Copyright 2018-Present Shanghai Yitu Technology Co., Ltd. 
# Licensed under the Apache License, Version 2.0

CONSTANT_VERSION = '0.1.0'

CONSTANT_REQUEST_TIMEOUT = 50

CONSTANT_AUE_PCM = 'pcm'
CONSTANT_AUE_AAC = 'aac'
CONSTANT_AUE_MP3 = 'mpeg2'

CONSTANT_LANG_MANDARIN = 1

CONSTANT_SCENE_GENERAL = 0

CONSTANT_AUE_SET = (CONSTANT_AUE_PCM, CONSTANT_AUE_AAC, CONSTANT_AUE_MP3)
